name: btc_wallet
description: "A simple Bitcoin balance checker app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Network requests
  dio: ^5.3.2

  # NFC functionality
  nfc_manager: ^3.3.0

  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true